
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Committee` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Committee
 * 
 */
export type CommitteeModel = runtime.Types.Result.DefaultSelection<Prisma.$CommitteePayload>

export type AggregateCommittee = {
  _count: CommitteeCountAggregateOutputType | null
  _avg: CommitteeAvgAggregateOutputType | null
  _sum: CommitteeSumAggregateOutputType | null
  _min: CommitteeMinAggregateOutputType | null
  _max: CommitteeMaxAggregateOutputType | null
}

export type CommitteeAvgAggregateOutputType = {
  sortOrder: number | null
}

export type CommitteeSumAggregateOutputType = {
  sortOrder: number | null
}

export type CommitteeMinAggregateOutputType = {
  id: string | null
  name: string | null
  sortOrder: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CommitteeMaxAggregateOutputType = {
  id: string | null
  name: string | null
  sortOrder: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CommitteeCountAggregateOutputType = {
  id: number
  name: number
  members: number
  sortOrder: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CommitteeAvgAggregateInputType = {
  sortOrder?: true
}

export type CommitteeSumAggregateInputType = {
  sortOrder?: true
}

export type CommitteeMinAggregateInputType = {
  id?: true
  name?: true
  sortOrder?: true
  createdAt?: true
  updatedAt?: true
}

export type CommitteeMaxAggregateInputType = {
  id?: true
  name?: true
  sortOrder?: true
  createdAt?: true
  updatedAt?: true
}

export type CommitteeCountAggregateInputType = {
  id?: true
  name?: true
  members?: true
  sortOrder?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CommitteeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Committee to aggregate.
   */
  where?: Prisma.CommitteeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Committees to fetch.
   */
  orderBy?: Prisma.CommitteeOrderByWithRelationInput | Prisma.CommitteeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CommitteeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Committees from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Committees.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Committees
  **/
  _count?: true | CommitteeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CommitteeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CommitteeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CommitteeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CommitteeMaxAggregateInputType
}

export type GetCommitteeAggregateType<T extends CommitteeAggregateArgs> = {
      [P in keyof T & keyof AggregateCommittee]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCommittee[P]>
    : Prisma.GetScalarType<T[P], AggregateCommittee[P]>
}




export type CommitteeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CommitteeWhereInput
  orderBy?: Prisma.CommitteeOrderByWithAggregationInput | Prisma.CommitteeOrderByWithAggregationInput[]
  by: Prisma.CommitteeScalarFieldEnum[] | Prisma.CommitteeScalarFieldEnum
  having?: Prisma.CommitteeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CommitteeCountAggregateInputType | true
  _avg?: CommitteeAvgAggregateInputType
  _sum?: CommitteeSumAggregateInputType
  _min?: CommitteeMinAggregateInputType
  _max?: CommitteeMaxAggregateInputType
}

export type CommitteeGroupByOutputType = {
  id: string
  name: string
  members: string[]
  sortOrder: number
  createdAt: Date
  updatedAt: Date
  _count: CommitteeCountAggregateOutputType | null
  _avg: CommitteeAvgAggregateOutputType | null
  _sum: CommitteeSumAggregateOutputType | null
  _min: CommitteeMinAggregateOutputType | null
  _max: CommitteeMaxAggregateOutputType | null
}

export type GetCommitteeGroupByPayload<T extends CommitteeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CommitteeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CommitteeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CommitteeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CommitteeGroupByOutputType[P]>
      }
    >
  >



export type CommitteeWhereInput = {
  AND?: Prisma.CommitteeWhereInput | Prisma.CommitteeWhereInput[]
  OR?: Prisma.CommitteeWhereInput[]
  NOT?: Prisma.CommitteeWhereInput | Prisma.CommitteeWhereInput[]
  id?: Prisma.StringFilter<"Committee"> | string
  name?: Prisma.StringFilter<"Committee"> | string
  members?: Prisma.StringNullableListFilter<"Committee">
  sortOrder?: Prisma.IntFilter<"Committee"> | number
  createdAt?: Prisma.DateTimeFilter<"Committee"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Committee"> | Date | string
}

export type CommitteeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  members?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CommitteeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CommitteeWhereInput | Prisma.CommitteeWhereInput[]
  OR?: Prisma.CommitteeWhereInput[]
  NOT?: Prisma.CommitteeWhereInput | Prisma.CommitteeWhereInput[]
  name?: Prisma.StringFilter<"Committee"> | string
  members?: Prisma.StringNullableListFilter<"Committee">
  sortOrder?: Prisma.IntFilter<"Committee"> | number
  createdAt?: Prisma.DateTimeFilter<"Committee"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Committee"> | Date | string
}, "id">

export type CommitteeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  members?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.CommitteeCountOrderByAggregateInput
  _avg?: Prisma.CommitteeAvgOrderByAggregateInput
  _max?: Prisma.CommitteeMaxOrderByAggregateInput
  _min?: Prisma.CommitteeMinOrderByAggregateInput
  _sum?: Prisma.CommitteeSumOrderByAggregateInput
}

export type CommitteeScalarWhereWithAggregatesInput = {
  AND?: Prisma.CommitteeScalarWhereWithAggregatesInput | Prisma.CommitteeScalarWhereWithAggregatesInput[]
  OR?: Prisma.CommitteeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CommitteeScalarWhereWithAggregatesInput | Prisma.CommitteeScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Committee"> | string
  name?: Prisma.StringWithAggregatesFilter<"Committee"> | string
  members?: Prisma.StringNullableListFilter<"Committee">
  sortOrder?: Prisma.IntWithAggregatesFilter<"Committee"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Committee"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Committee"> | Date | string
}

export type CommitteeCreateInput = {
  id?: string
  name: string
  members?: Prisma.CommitteeCreatemembersInput | string[]
  sortOrder?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CommitteeUncheckedCreateInput = {
  id?: string
  name: string
  members?: Prisma.CommitteeCreatemembersInput | string[]
  sortOrder?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CommitteeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  members?: Prisma.CommitteeUpdatemembersInput | string[]
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CommitteeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  members?: Prisma.CommitteeUpdatemembersInput | string[]
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CommitteeCreateManyInput = {
  id?: string
  name: string
  members?: Prisma.CommitteeCreatemembersInput | string[]
  sortOrder?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CommitteeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  members?: Prisma.CommitteeUpdatemembersInput | string[]
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CommitteeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  members?: Prisma.CommitteeUpdatemembersInput | string[]
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CommitteeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  members?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CommitteeAvgOrderByAggregateInput = {
  sortOrder?: Prisma.SortOrder
}

export type CommitteeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CommitteeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CommitteeSumOrderByAggregateInput = {
  sortOrder?: Prisma.SortOrder
}

export type CommitteeCreatemembersInput = {
  set: string[]
}

export type CommitteeUpdatemembersInput = {
  set?: string[]
  push?: string | string[]
}



export type CommitteeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  members?: boolean
  sortOrder?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["committee"]>

export type CommitteeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  members?: boolean
  sortOrder?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["committee"]>

export type CommitteeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  members?: boolean
  sortOrder?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["committee"]>

export type CommitteeSelectScalar = {
  id?: boolean
  name?: boolean
  members?: boolean
  sortOrder?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CommitteeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "members" | "sortOrder" | "createdAt" | "updatedAt", ExtArgs["result"]["committee"]>

export type $CommitteePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Committee"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    members: string[]
    sortOrder: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["committee"]>
  composites: {}
}

export type CommitteeGetPayload<S extends boolean | null | undefined | CommitteeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CommitteePayload, S>

export type CommitteeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CommitteeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CommitteeCountAggregateInputType | true
  }

export interface CommitteeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Committee'], meta: { name: 'Committee' } }
  /**
   * Find zero or one Committee that matches the filter.
   * @param {CommitteeFindUniqueArgs} args - Arguments to find a Committee
   * @example
   * // Get one Committee
   * const committee = await prisma.committee.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CommitteeFindUniqueArgs>(args: Prisma.SelectSubset<T, CommitteeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CommitteeClient<runtime.Types.Result.GetResult<Prisma.$CommitteePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Committee that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CommitteeFindUniqueOrThrowArgs} args - Arguments to find a Committee
   * @example
   * // Get one Committee
   * const committee = await prisma.committee.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CommitteeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CommitteeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CommitteeClient<runtime.Types.Result.GetResult<Prisma.$CommitteePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Committee that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommitteeFindFirstArgs} args - Arguments to find a Committee
   * @example
   * // Get one Committee
   * const committee = await prisma.committee.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CommitteeFindFirstArgs>(args?: Prisma.SelectSubset<T, CommitteeFindFirstArgs<ExtArgs>>): Prisma.Prisma__CommitteeClient<runtime.Types.Result.GetResult<Prisma.$CommitteePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Committee that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommitteeFindFirstOrThrowArgs} args - Arguments to find a Committee
   * @example
   * // Get one Committee
   * const committee = await prisma.committee.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CommitteeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CommitteeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CommitteeClient<runtime.Types.Result.GetResult<Prisma.$CommitteePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Committees that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommitteeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Committees
   * const committees = await prisma.committee.findMany()
   * 
   * // Get first 10 Committees
   * const committees = await prisma.committee.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const committeeWithIdOnly = await prisma.committee.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CommitteeFindManyArgs>(args?: Prisma.SelectSubset<T, CommitteeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CommitteePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Committee.
   * @param {CommitteeCreateArgs} args - Arguments to create a Committee.
   * @example
   * // Create one Committee
   * const Committee = await prisma.committee.create({
   *   data: {
   *     // ... data to create a Committee
   *   }
   * })
   * 
   */
  create<T extends CommitteeCreateArgs>(args: Prisma.SelectSubset<T, CommitteeCreateArgs<ExtArgs>>): Prisma.Prisma__CommitteeClient<runtime.Types.Result.GetResult<Prisma.$CommitteePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Committees.
   * @param {CommitteeCreateManyArgs} args - Arguments to create many Committees.
   * @example
   * // Create many Committees
   * const committee = await prisma.committee.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CommitteeCreateManyArgs>(args?: Prisma.SelectSubset<T, CommitteeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Committees and returns the data saved in the database.
   * @param {CommitteeCreateManyAndReturnArgs} args - Arguments to create many Committees.
   * @example
   * // Create many Committees
   * const committee = await prisma.committee.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Committees and only return the `id`
   * const committeeWithIdOnly = await prisma.committee.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CommitteeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CommitteeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CommitteePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Committee.
   * @param {CommitteeDeleteArgs} args - Arguments to delete one Committee.
   * @example
   * // Delete one Committee
   * const Committee = await prisma.committee.delete({
   *   where: {
   *     // ... filter to delete one Committee
   *   }
   * })
   * 
   */
  delete<T extends CommitteeDeleteArgs>(args: Prisma.SelectSubset<T, CommitteeDeleteArgs<ExtArgs>>): Prisma.Prisma__CommitteeClient<runtime.Types.Result.GetResult<Prisma.$CommitteePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Committee.
   * @param {CommitteeUpdateArgs} args - Arguments to update one Committee.
   * @example
   * // Update one Committee
   * const committee = await prisma.committee.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CommitteeUpdateArgs>(args: Prisma.SelectSubset<T, CommitteeUpdateArgs<ExtArgs>>): Prisma.Prisma__CommitteeClient<runtime.Types.Result.GetResult<Prisma.$CommitteePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Committees.
   * @param {CommitteeDeleteManyArgs} args - Arguments to filter Committees to delete.
   * @example
   * // Delete a few Committees
   * const { count } = await prisma.committee.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CommitteeDeleteManyArgs>(args?: Prisma.SelectSubset<T, CommitteeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Committees.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommitteeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Committees
   * const committee = await prisma.committee.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CommitteeUpdateManyArgs>(args: Prisma.SelectSubset<T, CommitteeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Committees and returns the data updated in the database.
   * @param {CommitteeUpdateManyAndReturnArgs} args - Arguments to update many Committees.
   * @example
   * // Update many Committees
   * const committee = await prisma.committee.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Committees and only return the `id`
   * const committeeWithIdOnly = await prisma.committee.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CommitteeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CommitteeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CommitteePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Committee.
   * @param {CommitteeUpsertArgs} args - Arguments to update or create a Committee.
   * @example
   * // Update or create a Committee
   * const committee = await prisma.committee.upsert({
   *   create: {
   *     // ... data to create a Committee
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Committee we want to update
   *   }
   * })
   */
  upsert<T extends CommitteeUpsertArgs>(args: Prisma.SelectSubset<T, CommitteeUpsertArgs<ExtArgs>>): Prisma.Prisma__CommitteeClient<runtime.Types.Result.GetResult<Prisma.$CommitteePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Committees.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommitteeCountArgs} args - Arguments to filter Committees to count.
   * @example
   * // Count the number of Committees
   * const count = await prisma.committee.count({
   *   where: {
   *     // ... the filter for the Committees we want to count
   *   }
   * })
  **/
  count<T extends CommitteeCountArgs>(
    args?: Prisma.Subset<T, CommitteeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CommitteeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Committee.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommitteeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CommitteeAggregateArgs>(args: Prisma.Subset<T, CommitteeAggregateArgs>): Prisma.PrismaPromise<GetCommitteeAggregateType<T>>

  /**
   * Group by Committee.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommitteeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CommitteeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CommitteeGroupByArgs['orderBy'] }
      : { orderBy?: CommitteeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CommitteeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCommitteeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Committee model
 */
readonly fields: CommitteeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Committee.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CommitteeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Committee model
 */
export interface CommitteeFieldRefs {
  readonly id: Prisma.FieldRef<"Committee", 'String'>
  readonly name: Prisma.FieldRef<"Committee", 'String'>
  readonly members: Prisma.FieldRef<"Committee", 'String[]'>
  readonly sortOrder: Prisma.FieldRef<"Committee", 'Int'>
  readonly createdAt: Prisma.FieldRef<"Committee", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Committee", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Committee findUnique
 */
export type CommitteeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Committee
   */
  select?: Prisma.CommitteeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Committee
   */
  omit?: Prisma.CommitteeOmit<ExtArgs> | null
  /**
   * Filter, which Committee to fetch.
   */
  where: Prisma.CommitteeWhereUniqueInput
}

/**
 * Committee findUniqueOrThrow
 */
export type CommitteeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Committee
   */
  select?: Prisma.CommitteeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Committee
   */
  omit?: Prisma.CommitteeOmit<ExtArgs> | null
  /**
   * Filter, which Committee to fetch.
   */
  where: Prisma.CommitteeWhereUniqueInput
}

/**
 * Committee findFirst
 */
export type CommitteeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Committee
   */
  select?: Prisma.CommitteeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Committee
   */
  omit?: Prisma.CommitteeOmit<ExtArgs> | null
  /**
   * Filter, which Committee to fetch.
   */
  where?: Prisma.CommitteeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Committees to fetch.
   */
  orderBy?: Prisma.CommitteeOrderByWithRelationInput | Prisma.CommitteeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Committees.
   */
  cursor?: Prisma.CommitteeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Committees from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Committees.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Committees.
   */
  distinct?: Prisma.CommitteeScalarFieldEnum | Prisma.CommitteeScalarFieldEnum[]
}

/**
 * Committee findFirstOrThrow
 */
export type CommitteeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Committee
   */
  select?: Prisma.CommitteeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Committee
   */
  omit?: Prisma.CommitteeOmit<ExtArgs> | null
  /**
   * Filter, which Committee to fetch.
   */
  where?: Prisma.CommitteeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Committees to fetch.
   */
  orderBy?: Prisma.CommitteeOrderByWithRelationInput | Prisma.CommitteeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Committees.
   */
  cursor?: Prisma.CommitteeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Committees from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Committees.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Committees.
   */
  distinct?: Prisma.CommitteeScalarFieldEnum | Prisma.CommitteeScalarFieldEnum[]
}

/**
 * Committee findMany
 */
export type CommitteeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Committee
   */
  select?: Prisma.CommitteeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Committee
   */
  omit?: Prisma.CommitteeOmit<ExtArgs> | null
  /**
   * Filter, which Committees to fetch.
   */
  where?: Prisma.CommitteeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Committees to fetch.
   */
  orderBy?: Prisma.CommitteeOrderByWithRelationInput | Prisma.CommitteeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Committees.
   */
  cursor?: Prisma.CommitteeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Committees from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Committees.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Committees.
   */
  distinct?: Prisma.CommitteeScalarFieldEnum | Prisma.CommitteeScalarFieldEnum[]
}

/**
 * Committee create
 */
export type CommitteeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Committee
   */
  select?: Prisma.CommitteeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Committee
   */
  omit?: Prisma.CommitteeOmit<ExtArgs> | null
  /**
   * The data needed to create a Committee.
   */
  data: Prisma.XOR<Prisma.CommitteeCreateInput, Prisma.CommitteeUncheckedCreateInput>
}

/**
 * Committee createMany
 */
export type CommitteeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Committees.
   */
  data: Prisma.CommitteeCreateManyInput | Prisma.CommitteeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Committee createManyAndReturn
 */
export type CommitteeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Committee
   */
  select?: Prisma.CommitteeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Committee
   */
  omit?: Prisma.CommitteeOmit<ExtArgs> | null
  /**
   * The data used to create many Committees.
   */
  data: Prisma.CommitteeCreateManyInput | Prisma.CommitteeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Committee update
 */
export type CommitteeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Committee
   */
  select?: Prisma.CommitteeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Committee
   */
  omit?: Prisma.CommitteeOmit<ExtArgs> | null
  /**
   * The data needed to update a Committee.
   */
  data: Prisma.XOR<Prisma.CommitteeUpdateInput, Prisma.CommitteeUncheckedUpdateInput>
  /**
   * Choose, which Committee to update.
   */
  where: Prisma.CommitteeWhereUniqueInput
}

/**
 * Committee updateMany
 */
export type CommitteeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Committees.
   */
  data: Prisma.XOR<Prisma.CommitteeUpdateManyMutationInput, Prisma.CommitteeUncheckedUpdateManyInput>
  /**
   * Filter which Committees to update
   */
  where?: Prisma.CommitteeWhereInput
  /**
   * Limit how many Committees to update.
   */
  limit?: number
}

/**
 * Committee updateManyAndReturn
 */
export type CommitteeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Committee
   */
  select?: Prisma.CommitteeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Committee
   */
  omit?: Prisma.CommitteeOmit<ExtArgs> | null
  /**
   * The data used to update Committees.
   */
  data: Prisma.XOR<Prisma.CommitteeUpdateManyMutationInput, Prisma.CommitteeUncheckedUpdateManyInput>
  /**
   * Filter which Committees to update
   */
  where?: Prisma.CommitteeWhereInput
  /**
   * Limit how many Committees to update.
   */
  limit?: number
}

/**
 * Committee upsert
 */
export type CommitteeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Committee
   */
  select?: Prisma.CommitteeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Committee
   */
  omit?: Prisma.CommitteeOmit<ExtArgs> | null
  /**
   * The filter to search for the Committee to update in case it exists.
   */
  where: Prisma.CommitteeWhereUniqueInput
  /**
   * In case the Committee found by the `where` argument doesn't exist, create a new Committee with this data.
   */
  create: Prisma.XOR<Prisma.CommitteeCreateInput, Prisma.CommitteeUncheckedCreateInput>
  /**
   * In case the Committee was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CommitteeUpdateInput, Prisma.CommitteeUncheckedUpdateInput>
}

/**
 * Committee delete
 */
export type CommitteeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Committee
   */
  select?: Prisma.CommitteeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Committee
   */
  omit?: Prisma.CommitteeOmit<ExtArgs> | null
  /**
   * Filter which Committee to delete.
   */
  where: Prisma.CommitteeWhereUniqueInput
}

/**
 * Committee deleteMany
 */
export type CommitteeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Committees to delete
   */
  where?: Prisma.CommitteeWhereInput
  /**
   * Limit how many Committees to delete.
   */
  limit?: number
}

/**
 * Committee without action
 */
export type CommitteeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Committee
   */
  select?: Prisma.CommitteeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Committee
   */
  omit?: Prisma.CommitteeOmit<ExtArgs> | null
}
