
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MaintenanceCompany` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model MaintenanceCompany
 * 
 */
export type MaintenanceCompanyModel = runtime.Types.Result.DefaultSelection<Prisma.$MaintenanceCompanyPayload>

export type AggregateMaintenanceCompany = {
  _count: MaintenanceCompanyCountAggregateOutputType | null
  _min: MaintenanceCompanyMinAggregateOutputType | null
  _max: MaintenanceCompanyMaxAggregateOutputType | null
}

export type MaintenanceCompanyMinAggregateOutputType = {
  id: string | null
  name: string | null
  street: string | null
  state: string | null
  zip: string | null
  phone: string | null
  email: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MaintenanceCompanyMaxAggregateOutputType = {
  id: string | null
  name: string | null
  street: string | null
  state: string | null
  zip: string | null
  phone: string | null
  email: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MaintenanceCompanyCountAggregateOutputType = {
  id: number
  name: number
  street: number
  state: number
  zip: number
  phone: number
  email: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type MaintenanceCompanyMinAggregateInputType = {
  id?: true
  name?: true
  street?: true
  state?: true
  zip?: true
  phone?: true
  email?: true
  createdAt?: true
  updatedAt?: true
}

export type MaintenanceCompanyMaxAggregateInputType = {
  id?: true
  name?: true
  street?: true
  state?: true
  zip?: true
  phone?: true
  email?: true
  createdAt?: true
  updatedAt?: true
}

export type MaintenanceCompanyCountAggregateInputType = {
  id?: true
  name?: true
  street?: true
  state?: true
  zip?: true
  phone?: true
  email?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type MaintenanceCompanyAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MaintenanceCompany to aggregate.
   */
  where?: Prisma.MaintenanceCompanyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MaintenanceCompanies to fetch.
   */
  orderBy?: Prisma.MaintenanceCompanyOrderByWithRelationInput | Prisma.MaintenanceCompanyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MaintenanceCompanyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MaintenanceCompanies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MaintenanceCompanies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MaintenanceCompanies
  **/
  _count?: true | MaintenanceCompanyCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MaintenanceCompanyMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MaintenanceCompanyMaxAggregateInputType
}

export type GetMaintenanceCompanyAggregateType<T extends MaintenanceCompanyAggregateArgs> = {
      [P in keyof T & keyof AggregateMaintenanceCompany]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMaintenanceCompany[P]>
    : Prisma.GetScalarType<T[P], AggregateMaintenanceCompany[P]>
}




export type MaintenanceCompanyGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MaintenanceCompanyWhereInput
  orderBy?: Prisma.MaintenanceCompanyOrderByWithAggregationInput | Prisma.MaintenanceCompanyOrderByWithAggregationInput[]
  by: Prisma.MaintenanceCompanyScalarFieldEnum[] | Prisma.MaintenanceCompanyScalarFieldEnum
  having?: Prisma.MaintenanceCompanyScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MaintenanceCompanyCountAggregateInputType | true
  _min?: MaintenanceCompanyMinAggregateInputType
  _max?: MaintenanceCompanyMaxAggregateInputType
}

export type MaintenanceCompanyGroupByOutputType = {
  id: string
  name: string
  street: string
  state: string
  zip: string
  phone: string
  email: string
  createdAt: Date
  updatedAt: Date
  _count: MaintenanceCompanyCountAggregateOutputType | null
  _min: MaintenanceCompanyMinAggregateOutputType | null
  _max: MaintenanceCompanyMaxAggregateOutputType | null
}

export type GetMaintenanceCompanyGroupByPayload<T extends MaintenanceCompanyGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MaintenanceCompanyGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MaintenanceCompanyGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MaintenanceCompanyGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MaintenanceCompanyGroupByOutputType[P]>
      }
    >
  >



export type MaintenanceCompanyWhereInput = {
  AND?: Prisma.MaintenanceCompanyWhereInput | Prisma.MaintenanceCompanyWhereInput[]
  OR?: Prisma.MaintenanceCompanyWhereInput[]
  NOT?: Prisma.MaintenanceCompanyWhereInput | Prisma.MaintenanceCompanyWhereInput[]
  id?: Prisma.StringFilter<"MaintenanceCompany"> | string
  name?: Prisma.StringFilter<"MaintenanceCompany"> | string
  street?: Prisma.StringFilter<"MaintenanceCompany"> | string
  state?: Prisma.StringFilter<"MaintenanceCompany"> | string
  zip?: Prisma.StringFilter<"MaintenanceCompany"> | string
  phone?: Prisma.StringFilter<"MaintenanceCompany"> | string
  email?: Prisma.StringFilter<"MaintenanceCompany"> | string
  createdAt?: Prisma.DateTimeFilter<"MaintenanceCompany"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MaintenanceCompany"> | Date | string
}

export type MaintenanceCompanyOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  street?: Prisma.SortOrder
  state?: Prisma.SortOrder
  zip?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  email?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MaintenanceCompanyWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.MaintenanceCompanyWhereInput | Prisma.MaintenanceCompanyWhereInput[]
  OR?: Prisma.MaintenanceCompanyWhereInput[]
  NOT?: Prisma.MaintenanceCompanyWhereInput | Prisma.MaintenanceCompanyWhereInput[]
  name?: Prisma.StringFilter<"MaintenanceCompany"> | string
  street?: Prisma.StringFilter<"MaintenanceCompany"> | string
  state?: Prisma.StringFilter<"MaintenanceCompany"> | string
  zip?: Prisma.StringFilter<"MaintenanceCompany"> | string
  phone?: Prisma.StringFilter<"MaintenanceCompany"> | string
  email?: Prisma.StringFilter<"MaintenanceCompany"> | string
  createdAt?: Prisma.DateTimeFilter<"MaintenanceCompany"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MaintenanceCompany"> | Date | string
}, "id">

export type MaintenanceCompanyOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  street?: Prisma.SortOrder
  state?: Prisma.SortOrder
  zip?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  email?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.MaintenanceCompanyCountOrderByAggregateInput
  _max?: Prisma.MaintenanceCompanyMaxOrderByAggregateInput
  _min?: Prisma.MaintenanceCompanyMinOrderByAggregateInput
}

export type MaintenanceCompanyScalarWhereWithAggregatesInput = {
  AND?: Prisma.MaintenanceCompanyScalarWhereWithAggregatesInput | Prisma.MaintenanceCompanyScalarWhereWithAggregatesInput[]
  OR?: Prisma.MaintenanceCompanyScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MaintenanceCompanyScalarWhereWithAggregatesInput | Prisma.MaintenanceCompanyScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"MaintenanceCompany"> | string
  name?: Prisma.StringWithAggregatesFilter<"MaintenanceCompany"> | string
  street?: Prisma.StringWithAggregatesFilter<"MaintenanceCompany"> | string
  state?: Prisma.StringWithAggregatesFilter<"MaintenanceCompany"> | string
  zip?: Prisma.StringWithAggregatesFilter<"MaintenanceCompany"> | string
  phone?: Prisma.StringWithAggregatesFilter<"MaintenanceCompany"> | string
  email?: Prisma.StringWithAggregatesFilter<"MaintenanceCompany"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"MaintenanceCompany"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"MaintenanceCompany"> | Date | string
}

export type MaintenanceCompanyCreateInput = {
  id?: string
  name: string
  street: string
  state: string
  zip: string
  phone: string
  email: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MaintenanceCompanyUncheckedCreateInput = {
  id?: string
  name: string
  street: string
  state: string
  zip: string
  phone: string
  email: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MaintenanceCompanyUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  street?: Prisma.StringFieldUpdateOperationsInput | string
  state?: Prisma.StringFieldUpdateOperationsInput | string
  zip?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MaintenanceCompanyUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  street?: Prisma.StringFieldUpdateOperationsInput | string
  state?: Prisma.StringFieldUpdateOperationsInput | string
  zip?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MaintenanceCompanyCreateManyInput = {
  id?: string
  name: string
  street: string
  state: string
  zip: string
  phone: string
  email: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MaintenanceCompanyUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  street?: Prisma.StringFieldUpdateOperationsInput | string
  state?: Prisma.StringFieldUpdateOperationsInput | string
  zip?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MaintenanceCompanyUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  street?: Prisma.StringFieldUpdateOperationsInput | string
  state?: Prisma.StringFieldUpdateOperationsInput | string
  zip?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MaintenanceCompanyCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  street?: Prisma.SortOrder
  state?: Prisma.SortOrder
  zip?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  email?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MaintenanceCompanyMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  street?: Prisma.SortOrder
  state?: Prisma.SortOrder
  zip?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  email?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MaintenanceCompanyMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  street?: Prisma.SortOrder
  state?: Prisma.SortOrder
  zip?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  email?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}



export type MaintenanceCompanySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  street?: boolean
  state?: boolean
  zip?: boolean
  phone?: boolean
  email?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["maintenanceCompany"]>

export type MaintenanceCompanySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  street?: boolean
  state?: boolean
  zip?: boolean
  phone?: boolean
  email?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["maintenanceCompany"]>

export type MaintenanceCompanySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  street?: boolean
  state?: boolean
  zip?: boolean
  phone?: boolean
  email?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["maintenanceCompany"]>

export type MaintenanceCompanySelectScalar = {
  id?: boolean
  name?: boolean
  street?: boolean
  state?: boolean
  zip?: boolean
  phone?: boolean
  email?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type MaintenanceCompanyOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "street" | "state" | "zip" | "phone" | "email" | "createdAt" | "updatedAt", ExtArgs["result"]["maintenanceCompany"]>

export type $MaintenanceCompanyPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MaintenanceCompany"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    street: string
    state: string
    zip: string
    phone: string
    email: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["maintenanceCompany"]>
  composites: {}
}

export type MaintenanceCompanyGetPayload<S extends boolean | null | undefined | MaintenanceCompanyDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MaintenanceCompanyPayload, S>

export type MaintenanceCompanyCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MaintenanceCompanyFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MaintenanceCompanyCountAggregateInputType | true
  }

export interface MaintenanceCompanyDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MaintenanceCompany'], meta: { name: 'MaintenanceCompany' } }
  /**
   * Find zero or one MaintenanceCompany that matches the filter.
   * @param {MaintenanceCompanyFindUniqueArgs} args - Arguments to find a MaintenanceCompany
   * @example
   * // Get one MaintenanceCompany
   * const maintenanceCompany = await prisma.maintenanceCompany.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MaintenanceCompanyFindUniqueArgs>(args: Prisma.SelectSubset<T, MaintenanceCompanyFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MaintenanceCompanyClient<runtime.Types.Result.GetResult<Prisma.$MaintenanceCompanyPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MaintenanceCompany that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MaintenanceCompanyFindUniqueOrThrowArgs} args - Arguments to find a MaintenanceCompany
   * @example
   * // Get one MaintenanceCompany
   * const maintenanceCompany = await prisma.maintenanceCompany.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MaintenanceCompanyFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MaintenanceCompanyFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MaintenanceCompanyClient<runtime.Types.Result.GetResult<Prisma.$MaintenanceCompanyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MaintenanceCompany that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaintenanceCompanyFindFirstArgs} args - Arguments to find a MaintenanceCompany
   * @example
   * // Get one MaintenanceCompany
   * const maintenanceCompany = await prisma.maintenanceCompany.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MaintenanceCompanyFindFirstArgs>(args?: Prisma.SelectSubset<T, MaintenanceCompanyFindFirstArgs<ExtArgs>>): Prisma.Prisma__MaintenanceCompanyClient<runtime.Types.Result.GetResult<Prisma.$MaintenanceCompanyPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MaintenanceCompany that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaintenanceCompanyFindFirstOrThrowArgs} args - Arguments to find a MaintenanceCompany
   * @example
   * // Get one MaintenanceCompany
   * const maintenanceCompany = await prisma.maintenanceCompany.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MaintenanceCompanyFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MaintenanceCompanyFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MaintenanceCompanyClient<runtime.Types.Result.GetResult<Prisma.$MaintenanceCompanyPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MaintenanceCompanies that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaintenanceCompanyFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MaintenanceCompanies
   * const maintenanceCompanies = await prisma.maintenanceCompany.findMany()
   * 
   * // Get first 10 MaintenanceCompanies
   * const maintenanceCompanies = await prisma.maintenanceCompany.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const maintenanceCompanyWithIdOnly = await prisma.maintenanceCompany.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MaintenanceCompanyFindManyArgs>(args?: Prisma.SelectSubset<T, MaintenanceCompanyFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MaintenanceCompanyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MaintenanceCompany.
   * @param {MaintenanceCompanyCreateArgs} args - Arguments to create a MaintenanceCompany.
   * @example
   * // Create one MaintenanceCompany
   * const MaintenanceCompany = await prisma.maintenanceCompany.create({
   *   data: {
   *     // ... data to create a MaintenanceCompany
   *   }
   * })
   * 
   */
  create<T extends MaintenanceCompanyCreateArgs>(args: Prisma.SelectSubset<T, MaintenanceCompanyCreateArgs<ExtArgs>>): Prisma.Prisma__MaintenanceCompanyClient<runtime.Types.Result.GetResult<Prisma.$MaintenanceCompanyPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MaintenanceCompanies.
   * @param {MaintenanceCompanyCreateManyArgs} args - Arguments to create many MaintenanceCompanies.
   * @example
   * // Create many MaintenanceCompanies
   * const maintenanceCompany = await prisma.maintenanceCompany.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MaintenanceCompanyCreateManyArgs>(args?: Prisma.SelectSubset<T, MaintenanceCompanyCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MaintenanceCompanies and returns the data saved in the database.
   * @param {MaintenanceCompanyCreateManyAndReturnArgs} args - Arguments to create many MaintenanceCompanies.
   * @example
   * // Create many MaintenanceCompanies
   * const maintenanceCompany = await prisma.maintenanceCompany.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MaintenanceCompanies and only return the `id`
   * const maintenanceCompanyWithIdOnly = await prisma.maintenanceCompany.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MaintenanceCompanyCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MaintenanceCompanyCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MaintenanceCompanyPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MaintenanceCompany.
   * @param {MaintenanceCompanyDeleteArgs} args - Arguments to delete one MaintenanceCompany.
   * @example
   * // Delete one MaintenanceCompany
   * const MaintenanceCompany = await prisma.maintenanceCompany.delete({
   *   where: {
   *     // ... filter to delete one MaintenanceCompany
   *   }
   * })
   * 
   */
  delete<T extends MaintenanceCompanyDeleteArgs>(args: Prisma.SelectSubset<T, MaintenanceCompanyDeleteArgs<ExtArgs>>): Prisma.Prisma__MaintenanceCompanyClient<runtime.Types.Result.GetResult<Prisma.$MaintenanceCompanyPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MaintenanceCompany.
   * @param {MaintenanceCompanyUpdateArgs} args - Arguments to update one MaintenanceCompany.
   * @example
   * // Update one MaintenanceCompany
   * const maintenanceCompany = await prisma.maintenanceCompany.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MaintenanceCompanyUpdateArgs>(args: Prisma.SelectSubset<T, MaintenanceCompanyUpdateArgs<ExtArgs>>): Prisma.Prisma__MaintenanceCompanyClient<runtime.Types.Result.GetResult<Prisma.$MaintenanceCompanyPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MaintenanceCompanies.
   * @param {MaintenanceCompanyDeleteManyArgs} args - Arguments to filter MaintenanceCompanies to delete.
   * @example
   * // Delete a few MaintenanceCompanies
   * const { count } = await prisma.maintenanceCompany.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MaintenanceCompanyDeleteManyArgs>(args?: Prisma.SelectSubset<T, MaintenanceCompanyDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MaintenanceCompanies.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaintenanceCompanyUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MaintenanceCompanies
   * const maintenanceCompany = await prisma.maintenanceCompany.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MaintenanceCompanyUpdateManyArgs>(args: Prisma.SelectSubset<T, MaintenanceCompanyUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MaintenanceCompanies and returns the data updated in the database.
   * @param {MaintenanceCompanyUpdateManyAndReturnArgs} args - Arguments to update many MaintenanceCompanies.
   * @example
   * // Update many MaintenanceCompanies
   * const maintenanceCompany = await prisma.maintenanceCompany.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MaintenanceCompanies and only return the `id`
   * const maintenanceCompanyWithIdOnly = await prisma.maintenanceCompany.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MaintenanceCompanyUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MaintenanceCompanyUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MaintenanceCompanyPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MaintenanceCompany.
   * @param {MaintenanceCompanyUpsertArgs} args - Arguments to update or create a MaintenanceCompany.
   * @example
   * // Update or create a MaintenanceCompany
   * const maintenanceCompany = await prisma.maintenanceCompany.upsert({
   *   create: {
   *     // ... data to create a MaintenanceCompany
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MaintenanceCompany we want to update
   *   }
   * })
   */
  upsert<T extends MaintenanceCompanyUpsertArgs>(args: Prisma.SelectSubset<T, MaintenanceCompanyUpsertArgs<ExtArgs>>): Prisma.Prisma__MaintenanceCompanyClient<runtime.Types.Result.GetResult<Prisma.$MaintenanceCompanyPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MaintenanceCompanies.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaintenanceCompanyCountArgs} args - Arguments to filter MaintenanceCompanies to count.
   * @example
   * // Count the number of MaintenanceCompanies
   * const count = await prisma.maintenanceCompany.count({
   *   where: {
   *     // ... the filter for the MaintenanceCompanies we want to count
   *   }
   * })
  **/
  count<T extends MaintenanceCompanyCountArgs>(
    args?: Prisma.Subset<T, MaintenanceCompanyCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MaintenanceCompanyCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MaintenanceCompany.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaintenanceCompanyAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MaintenanceCompanyAggregateArgs>(args: Prisma.Subset<T, MaintenanceCompanyAggregateArgs>): Prisma.PrismaPromise<GetMaintenanceCompanyAggregateType<T>>

  /**
   * Group by MaintenanceCompany.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaintenanceCompanyGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MaintenanceCompanyGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MaintenanceCompanyGroupByArgs['orderBy'] }
      : { orderBy?: MaintenanceCompanyGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MaintenanceCompanyGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMaintenanceCompanyGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MaintenanceCompany model
 */
readonly fields: MaintenanceCompanyFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MaintenanceCompany.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MaintenanceCompanyClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MaintenanceCompany model
 */
export interface MaintenanceCompanyFieldRefs {
  readonly id: Prisma.FieldRef<"MaintenanceCompany", 'String'>
  readonly name: Prisma.FieldRef<"MaintenanceCompany", 'String'>
  readonly street: Prisma.FieldRef<"MaintenanceCompany", 'String'>
  readonly state: Prisma.FieldRef<"MaintenanceCompany", 'String'>
  readonly zip: Prisma.FieldRef<"MaintenanceCompany", 'String'>
  readonly phone: Prisma.FieldRef<"MaintenanceCompany", 'String'>
  readonly email: Prisma.FieldRef<"MaintenanceCompany", 'String'>
  readonly createdAt: Prisma.FieldRef<"MaintenanceCompany", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"MaintenanceCompany", 'DateTime'>
}
    

// Custom InputTypes
/**
 * MaintenanceCompany findUnique
 */
export type MaintenanceCompanyFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceCompany
   */
  select?: Prisma.MaintenanceCompanySelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceCompany
   */
  omit?: Prisma.MaintenanceCompanyOmit<ExtArgs> | null
  /**
   * Filter, which MaintenanceCompany to fetch.
   */
  where: Prisma.MaintenanceCompanyWhereUniqueInput
}

/**
 * MaintenanceCompany findUniqueOrThrow
 */
export type MaintenanceCompanyFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceCompany
   */
  select?: Prisma.MaintenanceCompanySelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceCompany
   */
  omit?: Prisma.MaintenanceCompanyOmit<ExtArgs> | null
  /**
   * Filter, which MaintenanceCompany to fetch.
   */
  where: Prisma.MaintenanceCompanyWhereUniqueInput
}

/**
 * MaintenanceCompany findFirst
 */
export type MaintenanceCompanyFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceCompany
   */
  select?: Prisma.MaintenanceCompanySelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceCompany
   */
  omit?: Prisma.MaintenanceCompanyOmit<ExtArgs> | null
  /**
   * Filter, which MaintenanceCompany to fetch.
   */
  where?: Prisma.MaintenanceCompanyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MaintenanceCompanies to fetch.
   */
  orderBy?: Prisma.MaintenanceCompanyOrderByWithRelationInput | Prisma.MaintenanceCompanyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MaintenanceCompanies.
   */
  cursor?: Prisma.MaintenanceCompanyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MaintenanceCompanies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MaintenanceCompanies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MaintenanceCompanies.
   */
  distinct?: Prisma.MaintenanceCompanyScalarFieldEnum | Prisma.MaintenanceCompanyScalarFieldEnum[]
}

/**
 * MaintenanceCompany findFirstOrThrow
 */
export type MaintenanceCompanyFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceCompany
   */
  select?: Prisma.MaintenanceCompanySelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceCompany
   */
  omit?: Prisma.MaintenanceCompanyOmit<ExtArgs> | null
  /**
   * Filter, which MaintenanceCompany to fetch.
   */
  where?: Prisma.MaintenanceCompanyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MaintenanceCompanies to fetch.
   */
  orderBy?: Prisma.MaintenanceCompanyOrderByWithRelationInput | Prisma.MaintenanceCompanyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MaintenanceCompanies.
   */
  cursor?: Prisma.MaintenanceCompanyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MaintenanceCompanies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MaintenanceCompanies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MaintenanceCompanies.
   */
  distinct?: Prisma.MaintenanceCompanyScalarFieldEnum | Prisma.MaintenanceCompanyScalarFieldEnum[]
}

/**
 * MaintenanceCompany findMany
 */
export type MaintenanceCompanyFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceCompany
   */
  select?: Prisma.MaintenanceCompanySelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceCompany
   */
  omit?: Prisma.MaintenanceCompanyOmit<ExtArgs> | null
  /**
   * Filter, which MaintenanceCompanies to fetch.
   */
  where?: Prisma.MaintenanceCompanyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MaintenanceCompanies to fetch.
   */
  orderBy?: Prisma.MaintenanceCompanyOrderByWithRelationInput | Prisma.MaintenanceCompanyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MaintenanceCompanies.
   */
  cursor?: Prisma.MaintenanceCompanyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MaintenanceCompanies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MaintenanceCompanies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MaintenanceCompanies.
   */
  distinct?: Prisma.MaintenanceCompanyScalarFieldEnum | Prisma.MaintenanceCompanyScalarFieldEnum[]
}

/**
 * MaintenanceCompany create
 */
export type MaintenanceCompanyCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceCompany
   */
  select?: Prisma.MaintenanceCompanySelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceCompany
   */
  omit?: Prisma.MaintenanceCompanyOmit<ExtArgs> | null
  /**
   * The data needed to create a MaintenanceCompany.
   */
  data: Prisma.XOR<Prisma.MaintenanceCompanyCreateInput, Prisma.MaintenanceCompanyUncheckedCreateInput>
}

/**
 * MaintenanceCompany createMany
 */
export type MaintenanceCompanyCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MaintenanceCompanies.
   */
  data: Prisma.MaintenanceCompanyCreateManyInput | Prisma.MaintenanceCompanyCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MaintenanceCompany createManyAndReturn
 */
export type MaintenanceCompanyCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceCompany
   */
  select?: Prisma.MaintenanceCompanySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceCompany
   */
  omit?: Prisma.MaintenanceCompanyOmit<ExtArgs> | null
  /**
   * The data used to create many MaintenanceCompanies.
   */
  data: Prisma.MaintenanceCompanyCreateManyInput | Prisma.MaintenanceCompanyCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MaintenanceCompany update
 */
export type MaintenanceCompanyUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceCompany
   */
  select?: Prisma.MaintenanceCompanySelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceCompany
   */
  omit?: Prisma.MaintenanceCompanyOmit<ExtArgs> | null
  /**
   * The data needed to update a MaintenanceCompany.
   */
  data: Prisma.XOR<Prisma.MaintenanceCompanyUpdateInput, Prisma.MaintenanceCompanyUncheckedUpdateInput>
  /**
   * Choose, which MaintenanceCompany to update.
   */
  where: Prisma.MaintenanceCompanyWhereUniqueInput
}

/**
 * MaintenanceCompany updateMany
 */
export type MaintenanceCompanyUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MaintenanceCompanies.
   */
  data: Prisma.XOR<Prisma.MaintenanceCompanyUpdateManyMutationInput, Prisma.MaintenanceCompanyUncheckedUpdateManyInput>
  /**
   * Filter which MaintenanceCompanies to update
   */
  where?: Prisma.MaintenanceCompanyWhereInput
  /**
   * Limit how many MaintenanceCompanies to update.
   */
  limit?: number
}

/**
 * MaintenanceCompany updateManyAndReturn
 */
export type MaintenanceCompanyUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceCompany
   */
  select?: Prisma.MaintenanceCompanySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceCompany
   */
  omit?: Prisma.MaintenanceCompanyOmit<ExtArgs> | null
  /**
   * The data used to update MaintenanceCompanies.
   */
  data: Prisma.XOR<Prisma.MaintenanceCompanyUpdateManyMutationInput, Prisma.MaintenanceCompanyUncheckedUpdateManyInput>
  /**
   * Filter which MaintenanceCompanies to update
   */
  where?: Prisma.MaintenanceCompanyWhereInput
  /**
   * Limit how many MaintenanceCompanies to update.
   */
  limit?: number
}

/**
 * MaintenanceCompany upsert
 */
export type MaintenanceCompanyUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceCompany
   */
  select?: Prisma.MaintenanceCompanySelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceCompany
   */
  omit?: Prisma.MaintenanceCompanyOmit<ExtArgs> | null
  /**
   * The filter to search for the MaintenanceCompany to update in case it exists.
   */
  where: Prisma.MaintenanceCompanyWhereUniqueInput
  /**
   * In case the MaintenanceCompany found by the `where` argument doesn't exist, create a new MaintenanceCompany with this data.
   */
  create: Prisma.XOR<Prisma.MaintenanceCompanyCreateInput, Prisma.MaintenanceCompanyUncheckedCreateInput>
  /**
   * In case the MaintenanceCompany was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MaintenanceCompanyUpdateInput, Prisma.MaintenanceCompanyUncheckedUpdateInput>
}

/**
 * MaintenanceCompany delete
 */
export type MaintenanceCompanyDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceCompany
   */
  select?: Prisma.MaintenanceCompanySelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceCompany
   */
  omit?: Prisma.MaintenanceCompanyOmit<ExtArgs> | null
  /**
   * Filter which MaintenanceCompany to delete.
   */
  where: Prisma.MaintenanceCompanyWhereUniqueInput
}

/**
 * MaintenanceCompany deleteMany
 */
export type MaintenanceCompanyDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MaintenanceCompanies to delete
   */
  where?: Prisma.MaintenanceCompanyWhereInput
  /**
   * Limit how many MaintenanceCompanies to delete.
   */
  limit?: number
}

/**
 * MaintenanceCompany without action
 */
export type MaintenanceCompanyDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceCompany
   */
  select?: Prisma.MaintenanceCompanySelect<ExtArgs> | null
  /**
   * Omit specific fields from the MaintenanceCompany
   */
  omit?: Prisma.MaintenanceCompanyOmit<ExtArgs> | null
}
